# Generated by Django 2.2.6 on 2019-10-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('genotype', models.CharField(max_length=255)),
                ('subject_id', models.CharField(max_length=255)),
                ('age_in_days', models.FloatField()),
                ('number_of_electrodes', models.IntegerField()),
                ('lab', models.CharField(max_length=255)),
                ('session_start_time', models.DateTimeField()),
                ('experimenter', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('session_description', models.CharField(max_length=1023)),
                ('institution', models.CharField(max_length=255)),
                ('number_of_units', models.IntegerField()),
                ('nwb_version', models.CharField(max_length=255)),
                ('related_publications', models.ManyToManyField(to='djaunty.Publication')),
            ],
        ),
    ]
