# Generated by Django 2.2.6 on 2019-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaunty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
