# Generated by Django 2.2.6 on 2019-10-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaunty', '0002_auto_20191026_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='age_in_days',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='experimenter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='genotype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='lab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='number_of_electrodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='number_of_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='nwb_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='session_description',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='session_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='species',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='subject_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
