# Generated by Django 2.2.6 on 2019-10-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaunty', '0005_auto_20191028_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='keywords',
            field=models.ManyToManyField(to='djaunty.Keyword'),
        ),
    ]
