# Generated by Django 2.2.6 on 2019-11-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djaunty', '0007_dataset_search_vector'),
    ]

    migration = """
        CREATE FUNCTION djaunty_text_search_update() RETURNS trigger as $$
        declare
            keywords text;
            publications text;
        begin
            SELECT
                string_agg(k.keyword, ' ') INTO keywords
            FROM djaunty_keyword k
            JOIN djaunty_dataset_keywords dk ON dk.keyword_id = k.id
            WHERE dk.dataset_id = NEW.id
            GROUP BY dk.dataset_id;

            SELECT
                string_agg(p.doi, ' ') INTO publications
            FROM djaunty_publication p
            JOIN djaunty_dataset_related_publications dp ON dp.publication_id = p.id
            WHERE dp.dataset_id = NEW.id
            GROUP BY dp.dataset_id;

            NEW.search_vector :=
                to_tsvector(coalesce(NEW.genotype, '')) ||
                to_tsvector(coalesce(NEW.lab, '')) ||
                to_tsvector(coalesce(NEW.experimenter, '')) ||
                to_tsvector(coalesce(NEW.species, '')) ||
                to_tsvector(coalesce(NEW.identifier, '')) ||
                to_tsvector(coalesce(NEW.session_description, '')) ||
                to_tsvector(coalesce(NEW.institution, '')) ||
                to_tsvector(coalesce(keywords, '')) ||
                to_tsvector(coalesce(publications, ''));

            return NEW;
        end
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER djaunty_text_search_trigger BEFORE INSERT OR UPDATE
            ON djaunty_dataset FOR EACH ROW EXECUTE PROCEDURE djaunty_text_search_update();

        -- Force trigger to run on all rows
        -- UPDATE djaunty_dataset SET id = id;
    """

    reverse_migration = """
        DROP TRIGGER djaunty_text_search_trigger ON djaunty_dataset;
        DROP FUNCTION djaunty_text_search_update;
    """

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
