# Generated by Django 2.2.6 on 2019-11-03 17:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djaunty', '0008_text_search_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dataset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='djaunty_dat_search__604251_gin'),
        ),
    ]
