# Generated by Django 2.2.6 on 2019-11-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaunty', '0009_auto_20191103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='keywords',
            field=models.ManyToManyField(related_name='datasets', to='djaunty.Keyword'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='related_publications',
            field=models.ManyToManyField(related_name='datasets', to='djaunty.Publication'),
        ),
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('datasets', models.ManyToManyField(related_name='tags', to='djaunty.Dataset')),
            ],
        ),
    ]
